name: Deploy to Cloud Functions from Source

on:
  push:
    branches:
      - master

env:
  PROJECT_ID: duong-dev
  REGION: australia-southeast1

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - uses: actions/checkout@v3

    - id: install
      run: |
        yarn install

    - id: lint
      run: |
        yarn run lint

    - id: compile
      run: |
        yarn run compile

    - id: auth
      uses: google-github-actions/auth@v0
      with:
        credentials_json: '${{ secrets.COVID_BOT_DEPLOY_SA_CREDENTIALS }}'

    - id: 'deploy'
      uses: 'google-github-actions/deploy-cloud-functions@v0'
      with:
        name: 'discord-covid-update'
        project_id: 'duong-dev'
        region: 'australia-southeast1'
        runtime: 'nodejs14'
        entry_point: 'covidBot'
        memory_mb: '128MB'
        event_trigger_type: google.pubsub.topic.publish
        event_trigger_resource: projects/duong-dev/topics/discord-covid-update2
        deploy_timeout: '30s'
        secret_environment_variables: 'TARGET_SERVERS=projects/374547579835/secrets/TARGET_SERVERS/versions/3'
